### ISSUE TITLE
spider: failed to add "new" domains

### ISSUE THREAD

**Issue by nicolasb827** [iredmail/iRedMail#222] opened 2023-06-20 22:00 UTC
- Spider 2.3.0 / 10 mailboxes
- installed via install.sh (upgraded from 2.2)
- AlmaLinux 4.18.0-425.19.2.el8_7.x86_64

Hello,
I am not able to add my own domain on spider web form.
<img width="1098" alt="Capture d’écran 2023-06-20 à 23 51 13" src="https://github.com/iredmail/iRedMail/assets/3798825/1571880c-20fb-4bd1-bd58-0ee3ff909efe">
<img width="1114" alt="Capture d’écran 2023-06-20 à 23 51 17" src="https://github.com/iredmail/iRedMail/assets/3798825/bd85b54d-9a14-402f-9087-d3fee09a6a89">

This is my personal domain, and the same error exists when trying to build a certificate for a .email extension on the front.

Is there a configuration key to add or a way to deactivate any check on the domain names ?
Thank you

**Comment by iredmail** [comment] 2023-06-21 00:25
What's the real email domain name? `b2.network`?
Might be caused by our regular expression used to filter email domain name, but i need the real email domain name to reproduce it.

**Comment by nicolasb827** [comment] 2023-06-21 10:06
yes, this is the real domain. I also own b2.systems and some 'exotic' domains :) (2b.immo ...)

**Comment by nicolasb827** [comment] 2023-06-21 10:41
on my side, I just check that a MX domain entry exists, to avoid validation using regex, when I have to handle domains. I think it should be a good solution. 
Why we would like to archive email from a domain that has no MX ?

**Comment by iredmail** [comment] 2023-06-22 05:45
This has been fixed in development edition, will release v2.4.0 soon.

One breaking change in v2.4.0: It now requires a license key.
Maybe we should release v2.3.1 with this fix and free for 10 mailboxes.

**Comment by nicolasb827** [comment] 2023-06-22 09:48
Great, i am ok to test an earlier release or a hot fix ^^

**Comment by iredmail** [comment] 2023-06-23 07:33
> Great, i am ok to test an earlier release or a hot fix ^^

Please sign up and tell me your email address (either username part of full email address is ok), then I will send you a beta release: 
https://store.iredmail.org/

thank you very much for helping. :)

**Comment by nicolasb827** [comment] 2023-06-23 22:17
my email:
nbelan @b2 . network (w/o spaces)

**Comment by iredmail** [comment] 2023-06-25 06:57
hi @nicolasb827 

Spider Email Archiver v2.4.0 is out. You can now get a free trial license after signed up:
https://store.iredmail.org/

v2.4.0 fixes the issue you reported in this thread. :)

**Closed by iredmail** 2023-06-25 06:57 UTC

**Comment by iredmail** [comment] 2023-06-25 07:05
Release Notes:
----
```
Dear all,

Spider Email Archiver v2.4.0 has been released.

- Download: https://spiderd.io/
- Docker edition is available here: https://hub.docker.com/r/iredmail/spider
- Install or upgrade: https://spiderd.io/docs/install.html

Below are the major changes that we have made since v2.3.0.
Don't forget to subscribe to our newsletter so that you won't
miss any news of Spider Email Archiver: https://spiderd.io/

## Breaking changes

Free license for up to 10 mailboxes is gone. A license key is now always required.
Sign up to get a free trial license (with unlimited mailboxes support) or
purchase one: https://store.iredmail.org/

## Improvements

- Simplified event filters on SMTP Events page.
- Refactored SMTP queue info on Dashboard page.
- Add filters on Activities page.
- Display account display name and login username while editing account profile.
- Log more info of SMTP events.
- spider-import:
   - It now supports importing from specified IMAP folders instead of all
     folders (argument `--imap-folder`). Multiple folders can be specified
     with multiple `--imap-folder` arguments. For example, to import emails
     from INBOX and Sent folders: `--imap-folder INBOX --imap-folder Sent`.
   - Simplified console output.

## Fixed issues

- Not set strict file permission on log files (it's now 0700).
- Not rotate web log file.
- Not start and stop components in proper order. This may cause database
 access error after closed databases.
- Several minor web UI display issues.

Thank you for choosing Spider Email Archiver, and we hope you
enjoy using this latest version. If you have any questions or concerns,
please don't hesitate to reach out to our support team.
```
