### ISSUE TITLE
installer breaks on sogo unknown packages

### ISSUE THREAD

**Issue by Dexus** [iredmail/iRedMail#29] opened 2020-05-02 15:13 UTC
I don't know right now where it breaks, if it was on iredmail or iredadmin, but if you enable all features and SOgo, it breaks on ubuntu 18.04 because it don't find all files for sogo.

Latest version of iredmail and iredadmin SQL 4.3 was used.

**Comment by iredmail** [comment] 2020-05-02 15:15
I don't understand what the problem is without any related log ... Will close this issue if no further log attached.

**Comment by Dexus** [comment] 2020-05-02 15:22
That is what i found in my open terminal:
```
reating/updating amavis user account...
Setting up libsope-ldap4.9 (4.9.r1664.20200429) ...
Setting up libsope-appserver4.9 (4.9.r1664.20200429) ...
Setting up sogo (4.3.0.20200430-1) ...
chmod: cannot access '/usr/share/doc/sogo/*.sh': No such file or directory
dpkg: error processing package sogo (--configure):
 installed sogo package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of sogo-activesync:No apport report written because the error message indicates its a followup error from a previous failure.
 sogo-activesync depends on sogo (= 4.3.0.20200430-1); however:
  Package sogo is not configured yet.

dpkg: error processing package sogo-activesync (--configure):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-20) ...

Processing triggers for ufw (0.35-5) ...
WARN: /etc/default is group writable!
WARN: /etc is group writable!
WARN: /usr is group writable!
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.13) ...
Processing triggers for dovecot-core (1:2.2.33.2-1ubuntu4.5) ...
Errors were encountered while processing:
 sogo
 sogo-activesync
E: Sub-process /usr/bin/dpkg returned an error code (1)
<< ERROR >> Installation failed, please check the terminal output.
<< ERROR >> If you're not sure what the problem is, try to get help in iRedMail
<< ERROR >> forum: https://forum.iredmail.org/
```

**Comment by iredmail** [comment] 2020-05-02 15:24
It's a SOGo packaging error, not iRedMail installer. :(

**Closed** 2020-05-04 04:30 UTC
